### ISSUE TITLE
TypeError when running ddr-import

### ISSUE THREAD

**Issue by gjost** [densho/ddr-local#182]
When running `ddr-import.py` I exported entity metadata from one of my test collections, `ddr-testing-268`, then made a few modifications in a text editor. I used the same csv for the import and got the attached error. Note that the script did successfully validate the headers and rows; it only blew up when attempting to import the first entity.
```
ddr@ddrworkbench-densho:/usr/local/src/ddr-local/ddrlocal/bin$ python ddr-import.py -u DDRAdmin -m dragontail@hq.densho.org -U gfroh -P PASSWORD /media/sf_ddrshared/ddr-testing-268-entity.csv /var/www/media/base/ddr-testing-268
2015-01-21 16:35:23,648 INFO     Starting new HTTP connection (1): partner.densho.org
2015-01-21 16:35:28,770 DEBUG    "GET /workbench/kiroku/ HTTP/1.1" 302 None
2015-01-21 16:35:28,843 DEBUG    "GET /workbench/accounts/login/?next=/workbench/kiroku/ HTTP/1.1" 200 None
2015-01-21 16:35:29,032 DEBUG    "POST /workbench/accounts/login/ HTTP/1.1" 302 None
2015-01-21 16:35:29,106 DEBUG    "GET /workbench/ HTTP/1.1" 200 None
2015-01-21 16:35:29,181 DEBUG    "GET /workbench/api/0.1/accounts/user/ HTTP/1.1" 200 None
2015-01-21 16:35:29,182 DEBUG    r2.status_code 200
2015-01-21 16:35:29,185 DEBUG    session.git_name Geoff Froh
2015-01-21 16:35:29,185 DEBUG    session.git_mail geoff.froh@densho.org
2015-01-21 16:35:29,185 DEBUG    gfroh is logged in
2015-01-21 16:35:29,185 DEBUG    Getting entity IDs
2015-01-21 16:35:29,303 DEBUG    "GET /workbench/kiroku/ddr-testing-268/ HTTP/1.1" 200 None
2015-01-21 16:35:29,349 INFO     Validating headers
2015-01-21 16:35:29,349 INFO     Validating headers
2015-01-21 16:35:29,349 INFO     Validating rows
2015-01-21 16:35:29,349 INFO     Validating rows
2015-01-21 16:35:29,353 INFO     1/3 - ddr-testing-268-1
2015-01-21 16:35:29,359 DEBUG        writing /var/www/media/base/ddr-testing-268/files/ddr-testing-268-1/entity.json
Traceback (most recent call last):
  File "ddr-import.py", line 239, in <module>
    main()
  File "ddr-import.py", line 194, in main
    args.user, args.mail, 'ddr-import'
  File "/usr/local/lib/python2.7/dist-packages/DDR/batch.py", line 620, in update_entities
    logging.debug(repo)
  File "/usr/lib/python2.7/logging/__init__.py", line 1618, in debug
    root.debug(msg, *args, **kwargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1136, in debug
    self._log(DEBUG, msg, args, **kwargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1267, in _log
    self.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1277, in handle
    self.callHandlers(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1317, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 744, in handle
    rv = self.filter(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 608, in filter
    if not f.filter(record):
  File "/usr/local/src/ddr-local/ddrlocal/webui/log.py", line 23, in filter
    msg_starting_http = RE_STARTING_HTTP.search(record.msg)
TypeError: expected string or buffer
ddr@ddrworkbench-densho:/usr/local/src/ddr-local/ddrlocal/bin$
```

**Comment by gjost** [comment]
This was a `ddr-cmdln` bug.  Fixed in commit 2d10480859
