### ISSUE TITLE
Can't export objects/files CSV

### ISSUE THREAD

**Issue by gjost** [densho/ddr-local#204]
Clicking on "export csv objects" or "export csv files" in the collection footer starts a task but the task fails.

For objects you get the following traceback:

```
Traceback (most recent call last):
  File "/usr/local/src/env/ddrlocal/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/src/env/ddrlocal/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/local/src/ddr-local/ddrlocal/webui/tasks.py", line 804, in csv_export_model
    csv_path = export_entities(collection_path, csv_path)
  File "/usr/local/src/ddr-local/ddrlocal/migration/densho.py", line 847, in export_entities
    fieldnames = [field['name'] for field in entitymodule.ENTITY_FIELDS]
AttributeError: 'module' object has no attribute 'ENTITY_FIELDS'
```

For files you just get the result with no traceback:

```
AttributeError("'module' object has no attribute 'FILE_FIELDS'",)
```

**Comment by gjost** [comment]
Ack!  This is using `ddrlocal/migration/densho.py` which really should have been retired a long time ago.  It's been superseded by `ddr-export` and `ddr-import` but those arent' really integrated into the UI.

**Comment by gjost** [comment]
Must have been fixed bc it's working now.
