### ISSUE TITLE
Could not upload ONLC_3635_1700dpi.tif to ddr-one-2-455

### ISSUE THREAD

**Issue by gjost** [densho/ddr-local#205]
```
entity_id	ddr-one-2-455
Task ID     0ee7342c-f07a-4ad7-b4ad-dd551d98d678

Traceback (most recent call last):
  File "/usr/local/src/env/ddrlocal/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/src/env/ddrlocal/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/local/src/ddr-local/ddrlocal/webui/tasks.py", line 256, in entity_add_file
    file_,repo,log = entity.add_file_commit(file_, repo, log, git_name, git_mail, agent)
  File "/usr/local/src/env/ddrlocal/local/lib/python2.7/site-packages/ddr_cmdln-0.9.4b0-py2.7.egg/DDR/models/__init__.py", line 1255, in add_file_commit
    return ingest.add_file_commit(self, file_, repo, log, git_name, git_mail, agent)
  File "/usr/local/src/env/ddrlocal/local/lib/python2.7/site-packages/ddr_cmdln-0.9.4b0-py2.7.egg/DDR/ingest.py", line 579, in add_file_commit
    raise Exception()
Exception
```

**Comment by gjost** [comment]
Task failed because of a modified but unstaged `changelog` file prevented a commit.  Did an amnesty commit to clear it.

The `Exception` call in `DDR/ingest.add_file_commit` (line 579) needs a message.
