### ISSUE TITLE
signature_abs crashes when saving objects

### ISSUE THREAD

**Issue by gjost** [densho/ddr-local#234]
This prevents object-save tasks from completing.
```
Traceback (most recent call last):
  File "/opt/ddr-local/venv/ddrlocal/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/ddr-local/venv/ddrlocal/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/ddr-local/ddrlocal/webui/tasks.py", line 639, in entity_edit
    form_data
  File "/opt/ddr-local/ddrlocal/webui/models.py", line 653, in save
    docstore.Docstore().post(self)
  File "/opt/ddr-local/venv/ddrlocal/local/lib/python2.7/site-packages/ddr_cmdln-0.9.4b0-py2.7.egg/DDR/docstore.py", line 639, in post
    publishable = _publishable([document.identifier.path_abs()], parents)
  File "/opt/ddr-local/venv/ddrlocal/local/lib/python2.7/site-packages/ddr_cmdln-0.9.4b0-py2.7.egg/DDR/docstore.py", line 1286, in _publishable
    with open(path, 'r') as f:
IOError: [Errno 21] Is a directory: '/var/www/media/ddr/ddr-testing-40017/files/ddr-testing-40017-1'
```

**Comment by gjost** [comment]
Fixed in commit 452cdfd.
