### ISSUE TITLE
only ddr user can use ddr command

### ISSUE THREAD

**Issue by gjost** [densho/ddr-local#86]
With the current setup only the `ddr` user can use the `ddr` command.  If any other user tries to use `ddr` they get a permissions error:

```
gjost@pnr:~$ ddr
Traceback (most recent call last):
  File "/usr/local/bin/ddr", line 43, in <module>
    logging.basicConfig(format=LOGGING_FORMAT, datefmt=LOGGING_DATEFMT, level=logging.DEBUG, filename=LOGGING_FILE)
  File "/usr/lib/python2.7/logging/__init__.py", line 1528, in basicConfig
    hdlr = FileHandler(filename, mode)
  File "/usr/lib/python2.7/logging/__init__.py", line 901, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python2.7/logging/__init__.py", line 924, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 13] Permission denied: '/var/log/ddr/local.log'
```

**Comment by gjost** [comment]
Logs should probably be owned by a the `ddr` group and chmodded to `775`.

**Comment by gjost** [comment]
This is kinda baked into the design of the system at this point.
